# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nodere/chupa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nodere/chupa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nodere/chupa/CMakeFiles /home/nodere/chupa//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nodere/chupa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chupa

# Build rule for target.
chupa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chupa
.PHONY : chupa

# fast build rule for target.
chupa/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/build
.PHONY : chupa/fast

gameclasses/fireball.o: gameclasses/fireball.cpp.o
.PHONY : gameclasses/fireball.o

# target to build an object file
gameclasses/fireball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/fireball.cpp.o
.PHONY : gameclasses/fireball.cpp.o

gameclasses/fireball.i: gameclasses/fireball.cpp.i
.PHONY : gameclasses/fireball.i

# target to preprocess a source file
gameclasses/fireball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/fireball.cpp.i
.PHONY : gameclasses/fireball.cpp.i

gameclasses/fireball.s: gameclasses/fireball.cpp.s
.PHONY : gameclasses/fireball.s

# target to generate assembly for a file
gameclasses/fireball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/fireball.cpp.s
.PHONY : gameclasses/fireball.cpp.s

gameclasses/game.o: gameclasses/game.cpp.o
.PHONY : gameclasses/game.o

# target to build an object file
gameclasses/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/game.cpp.o
.PHONY : gameclasses/game.cpp.o

gameclasses/game.i: gameclasses/game.cpp.i
.PHONY : gameclasses/game.i

# target to preprocess a source file
gameclasses/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/game.cpp.i
.PHONY : gameclasses/game.cpp.i

gameclasses/game.s: gameclasses/game.cpp.s
.PHONY : gameclasses/game.s

# target to generate assembly for a file
gameclasses/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/game.cpp.s
.PHONY : gameclasses/game.cpp.s

gameclasses/game_obj.o: gameclasses/game_obj.cpp.o
.PHONY : gameclasses/game_obj.o

# target to build an object file
gameclasses/game_obj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/game_obj.cpp.o
.PHONY : gameclasses/game_obj.cpp.o

gameclasses/game_obj.i: gameclasses/game_obj.cpp.i
.PHONY : gameclasses/game_obj.i

# target to preprocess a source file
gameclasses/game_obj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/game_obj.cpp.i
.PHONY : gameclasses/game_obj.cpp.i

gameclasses/game_obj.s: gameclasses/game_obj.cpp.s
.PHONY : gameclasses/game_obj.s

# target to generate assembly for a file
gameclasses/game_obj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/game_obj.cpp.s
.PHONY : gameclasses/game_obj.cpp.s

gameclasses/player.o: gameclasses/player.cpp.o
.PHONY : gameclasses/player.o

# target to build an object file
gameclasses/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/player.cpp.o
.PHONY : gameclasses/player.cpp.o

gameclasses/player.i: gameclasses/player.cpp.i
.PHONY : gameclasses/player.i

# target to preprocess a source file
gameclasses/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/player.cpp.i
.PHONY : gameclasses/player.cpp.i

gameclasses/player.s: gameclasses/player.cpp.s
.PHONY : gameclasses/player.s

# target to generate assembly for a file
gameclasses/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/player.cpp.s
.PHONY : gameclasses/player.cpp.s

gameclasses/target.o: gameclasses/target.cpp.o
.PHONY : gameclasses/target.o

# target to build an object file
gameclasses/target.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/target.cpp.o
.PHONY : gameclasses/target.cpp.o

gameclasses/target.i: gameclasses/target.cpp.i
.PHONY : gameclasses/target.i

# target to preprocess a source file
gameclasses/target.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/target.cpp.i
.PHONY : gameclasses/target.cpp.i

gameclasses/target.s: gameclasses/target.cpp.s
.PHONY : gameclasses/target.s

# target to generate assembly for a file
gameclasses/target.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/target.cpp.s
.PHONY : gameclasses/target.cpp.s

gameclasses/texture_handler.o: gameclasses/texture_handler.cpp.o
.PHONY : gameclasses/texture_handler.o

# target to build an object file
gameclasses/texture_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/texture_handler.cpp.o
.PHONY : gameclasses/texture_handler.cpp.o

gameclasses/texture_handler.i: gameclasses/texture_handler.cpp.i
.PHONY : gameclasses/texture_handler.i

# target to preprocess a source file
gameclasses/texture_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/texture_handler.cpp.i
.PHONY : gameclasses/texture_handler.cpp.i

gameclasses/texture_handler.s: gameclasses/texture_handler.cpp.s
.PHONY : gameclasses/texture_handler.s

# target to generate assembly for a file
gameclasses/texture_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/gameclasses/texture_handler.cpp.s
.PHONY : gameclasses/texture_handler.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chupa.dir/build.make CMakeFiles/chupa.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chupa"
	@echo "... gameclasses/fireball.o"
	@echo "... gameclasses/fireball.i"
	@echo "... gameclasses/fireball.s"
	@echo "... gameclasses/game.o"
	@echo "... gameclasses/game.i"
	@echo "... gameclasses/game.s"
	@echo "... gameclasses/game_obj.o"
	@echo "... gameclasses/game_obj.i"
	@echo "... gameclasses/game_obj.s"
	@echo "... gameclasses/player.o"
	@echo "... gameclasses/player.i"
	@echo "... gameclasses/player.s"
	@echo "... gameclasses/target.o"
	@echo "... gameclasses/target.i"
	@echo "... gameclasses/target.s"
	@echo "... gameclasses/texture_handler.o"
	@echo "... gameclasses/texture_handler.i"
	@echo "... gameclasses/texture_handler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

